

POST http://localhost:3100/api/v1/addUser
Content-Type:  application/json
{
    "szUserName":"pradeep"
}



###
POST  http://localhost:3100/api/v1/editUser
Content-Type:  application/json
{
  "id":"1",
}

###
POST  http://localhost:3100/api/v1/updateUser
Content-Type:  application/json
{
  "id":"1",
}


###
POST  http://localhost:3100/api/v1/deleteUser
Content-Type:  application/json
{
  "id":"1",
}

###
GET http://localhost:3100/api/v1/getUser



